name: Deploy Serverless Architecture with GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # AWS Credential configuration
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Pytest on Lambda function
    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Lambda/requirements.txt

    - name: Performing PyTest on MyLambdaCounter
      run: python -m pytest Lambda/test_LambdaCounter.py

    # Deploy the architecture HOORAH!!!
    - name: SAM Deploy
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "deploy -t template.yml"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
